### ISSUE TITLE
Issue in Cloning Repositories from GitHub

### ISSUE THREAD

**Issue by richagupta8nov** [thoughtworks/talisman#250] opened 2020-09-08 09:25 UTC
@harinee 

Hi 

we are facing an issue in cloning the repo from GitHub after talisman installation, it's happening on two different computers, request you to please resolve it asap, as its very urgent.

Please cheque with the screenshot.

![image (1)](https://user-images.githubusercontent.com/29193279/92458658-52f6d600-f1e3-11ea-8dad-bbdccaa3db96.png)

**Comment by svishwanath-tw** [comment] 2020-09-08 09:31
Have you tried install talisman using releases ?

We publish releases @ https://github.com/thoughtworks/talisman/releases .

**Comment by svishwanath-tw** [comment] 2020-09-08 09:32
Have you also tried the official installation method: https://github.com/thoughtworks/talisman#installation-as-a-global-hook-template

**Comment by richagupta8nov** [comment] 2020-09-08 09:38
@svishwanath-tw 
Hi
I have installed as below
1) open git bash in the root directory
2) and paste below command (pre commit-global)
curl --silent  https://raw.githubusercontent.com/thoughtworks/talisman/master/global_install_scripts/install.bash > /tmp/install_talisman.bash && /bin/bash /tmp/install_talisman.bash
3) after that it got installed

**Comment by harinee** [comment] 2020-09-08 09:44
@richagupta8nov also please confirm your talisman version.
`talisman -v` 

Also, incase you had uninstalled and then re-installed, there is an open issue ( https://github.com/thoughtworks/talisman/issues/232 ) which states currently Talisman doesn't remove hooks on uninstallation. So you might have to remove them manually before re-installation.

**Comment by richagupta8nov** [comment] 2020-09-08 09:49
@harinee @svishwanath-tw 

I have freshly installed on my 2 colleagues computer, I have not uninstalled it, and both are facing the same issue in cloning repo from GitHub, infact I tried to clone the repo on different paths, but still the same issue coming.

**Comment by svishwanath-tw** [comment] 2020-09-08 10:04
@richagupta8nov : It looks like you are facing an issue with windows cmd.exe not supporting symlinks.

If I understand the situation correctly, talisman has been installed via git-bash and has also been setup as global hook.
The clone is being performed on cmd.exe, this is the source of the problem.

Can you use [git-bash](https://gitforwindows.org/) instead of cmd.exe  when cloning ?

**Comment by harinee** [comment] 2020-09-08 10:07
Ok couple of questions:
1. OS Version?
2. Are you using git bash?
3. Can you please try cloning a different repo (maybe talisman's own repo, or any other)? Something outside your org's? 
It might help in troubleshooting.

I just cloned into a repo (even with a path with spaces, just to check) and it works fine for me
<img width="469" alt="Screenshot 2020-09-08 at 3 35 37 PM" src="https://user-images.githubusercontent.com/1300665/92463248-31005200-f1e9-11ea-8fe3-ae9de6f8d9b6.png">

**Comment by richagupta8nov** [comment] 2020-09-08 10:23
@harinee 
using gitbash
Talisman version - 1.8
window 10

I have installed on more colleagues computer few days back, that was version 1.6, following the same steps, for him everything is working fine, with cmd or git bash, both r working.

**Comment by richagupta8nov** [comment] 2020-09-08 10:24
@harinee 
I have version 1.3, even that is working fine, when I m cloning. 

But the two computers on which 1.8 is installed, giving problems with cmd and git bash.

**Comment by richagupta8nov** [comment] 2020-09-08 10:26
@svishwanath-tw 

please check the above two posts of mine

**Comment by harinee** [comment] 2020-09-08 10:30
@richagupta8nov and same with cloning a repo from outside your org's too?

**Comment by richagupta8nov** [comment] 2020-09-08 10:36
![image](https://user-images.githubusercontent.com/29193279/92466095-3790c880-f1ed-11ea-95e8-dca26266fff6.png)

**Comment by richagupta8nov** [comment] 2020-09-08 10:41
@svishwanath-tw @harinee 

we tried to clone this also outside our org also, still same issue.

check with the screenshot, please.

![image](https://user-images.githubusercontent.com/29193279/92466448-ba198800-f1ed-11ea-80bd-ec6d82bb1b6c.png)

**Comment by dcRUSTy** [comment] 2020-09-08 11:01
@harinee what i observed is I can reproduce this issue if `git config --global init.templatedir` C:\Users\admin\.git-template\hooks\pre-commit is a symlink

**Comment by dcRUSTy** [comment] 2020-09-08 11:10
@richagupta8nov if there is a "pre-commit" file in C:\Users\DebarghyaNag\\.git-template\hooks
try replacing it with c:\Users\DebarghyaNag\\.talisman\bin\talisman_hook_script

**Comment by dcRUSTy** [comment] 2020-09-08 11:26
@harinee 
![Capture](https://user-images.githubusercontent.com/40319304/92470508-28614900-f1f4-11ea-9089-a0c421d21192.JPG)

**Comment by svishwanath-tw** [comment] 2020-09-08 11:32
None of our install scripts use mklink though. Our installation scripts is only targeted at bash shell based installs.
Wonder what caused this issue.

**Comment by dcRUSTy** [comment] 2020-09-08 11:34
https://github.com/thoughtworks/talisman/search?q=mklink&unscoped_q=mklink i too noticed it today

**Comment by svishwanath-tw** [comment] 2020-09-08 11:34
> None of our install scripts use mklink though. Our installation scripts is only targeted at bash shell based installs.
> Wonder what caused this issue.

I stand corrected. Since the original install script, it has grown considerably and there is OS specific `mklink`

**Comment by svishwanath-tw** [comment] 2020-09-08 11:38
@richagupta8nov @dcRUSTy : https://thoughtworks.zoom.us/j/94204297903

**Comment by dcRUSTy** [comment] 2020-09-08 14:38
Found something GIT is the culprit
@svishwanath-tw @harinee `https://github.com/git-for-windows/git/pull/156` 
`set MSYS=winsymlinks:nativestrict`
![git_win_symlink](https://user-images.githubusercontent.com/40319304/92490698-f3aebb00-f20e-11ea-881a-a8d201c34ea1.JPG)

**Comment by richagupta8nov** [comment] 2020-09-08 14:39
any solution to this

**Comment by svishwanath-tw** [comment] 2020-09-08 14:41
@richagupta8nov : ☝️

**Comment by dcRUSTy** [comment] 2020-09-09 07:50
@harinee @svishwanath-tw It affects `git init` as well.

@richagupta8nov It will be fixed soon for the time being 
Delete `pre-commit` file in `C:\Users\DebarghyaNag\.git-template\hooks` 
Copy `c:\Users\DebarghyaNag\.talisman\bin\talisman_hook_script` to `C:\Users\DebarghyaNag\.git-template\hooks`
And rename `talisman_hook_script` file in `C:\Users\DebarghyaNag\.git-template\hooks` to `pre-commit`

> OR

`set MSYS=winsymlinks:nativestrict` in Command prompt before `git clone`

**Comment by richagupta8nov** [comment] 2020-09-09 08:11
@dcRUSTy 

thanks a ton

**Closed** 2020-09-09 08:25 UTC

**Comment by dcRUSTy** [comment] 2020-09-12 11:14
@svishwanath-tw @harinee 
On Windows 10 (10.0.19041)
Before recent commit it was **incorrectly** falling into else ( `*)`  ) which was copying (ln -svf) pre-commit file in place of symlink (on windows) therefore this issue was not there
https://github.com/thoughtworks/talisman/blob/fc5554c370d3423cc744023bc1704bec900d0d0c/global_install_scripts/install.bash#L212-L221

From recent commit it is **correctly** going in `"windows") ` which makes symlink thus leads to this issue
https://github.com/thoughtworks/talisman/blob/74bcbe2fa59424de0e6c820384464bda0090599e/global_install_scripts/install.bash#L214-L226

**Comment by svishwanath-tw** [comment] 2020-09-13 17:49
Great find. We should drop case behaviour and just use `ln -svf` no ?

The other option is to develop natively for powershell / cmd.exe integration.

Thoughts ? (@harinee , @dineshba , @derwent-m ...)

**Comment by derwent-m-js** [comment] 2020-09-13 22:32
Do the "install to single project" instructions still work for you? https://github.com/thoughtworks/talisman#installation-to-a-single-project

**Comment by dcRUSTy** [comment] 2020-09-14 03:23
@svishwanath-tw 
>Great find. We should drop case behaviour and just use ln -svf no ?

I think yes

@derwent-m-js @harinee @svishwanath-tw 
>Do the "install to single project" instructions still work for you? https://github.com/thoughtworks/talisman#installation-to-a-single-project

https://github.com/thoughtworks/talisman/issues/198
https://github.com/thoughtworks/talisman/issues/198#issuecomment-689563708
