### ISSUE TITLE
bug: bad error message when push is rejected due to remote changes

### ISSUE THREAD

**Issue by jacksingleton** [thoughtworks/talisman#25] opened 2017-03-11 07:35 UTC
```
$ git push
FATA[0000] Command execution failed                      error=exit status 128 output=
error: failed to push some refs to 'git@github.com:...'

$ rm .git/hooks/pre-push

$ git push
To github.com:...
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:...'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by chadlwilson** [comment] 2017-09-17 17:39
I was trying to look at submitting a PR to patch this; as have seen this problem before myself and it had been bugging me, but now I can't seem to replicate it and it's driving me slightly mad. I'm possibly doing something stupid, but are there any specific conditions in the changeset that you think might be required to trigger it?

**Comment by svishwanath-tw** [comment] 2018-12-18 17:45
Is this still an issue @chadlwilson , @jacksingleton ?

**Comment by chadlwilson** [comment] 2018-12-26 03:20
@svishwanath-tw I haven't been using Talisman recently, but I suspect it still is, unless there have been any significant changes to the way Talisman interacts with the remote and/or error handling. Might have some time later this week to try and replicate and dig into this again.

**Comment by nossbigg** [comment] 2018-12-26 08:40
Can confirm @chadlwilson 's observation, Talisman just errors out when there are remote changes and your local repo isn't synced with the remote (just encountered it at work today). Would be useful if Talisman has more useful error messages.

**Comment by chadlwilson** [comment] 2018-12-26 08:57
Just had another look, and it looks like the (currently unreleased) changes in https://github.com/thoughtworks/talisman/commit/b88752c45848055f7a21e01b85b858088a92ab0e#diff-16dd05da593e4772e0a8eb01269e0fdf might have addressed it by switching to `.CombinedOutput()`, which is what I had experimented with locally to address it. Will test this out later.

**Comment by harinee** [comment] 2019-10-01 07:22
Closing this as a duplicate of https://github.com/thoughtworks/talisman/issues/10

**Closed by harinee** 2019-10-01 07:22 UTC
Labels: bug, duplicate

**Comment by Aletien** [comment] 2021-12-01 08:33
I just made a single change in the code and I experience the same issue while trying to push the code to github
![git buggie](https://user-images.githubusercontent.com/15227123/144199620-74fdcda4-2de9-4fac-98ea-b9ddb3b0a3e9.PNG)
...

**Comment by harinee** [comment] 2021-12-03 13:55
@Aletien The error does not seem to be triggered by Talisman. It seems to be a message from git saying that your main is not on the latest version. This should be solved by a pull/rebase.
Am I missing something else here?
