### ISSUE TITLE
Issues in using Talisman on windows

### ISSUE THREAD

**Issue by ni8walk3r** [thoughtworks/talisman#119] opened 2019-06-04 08:45 UTC
Hi Team,

I'm using Talisman on windows, after installing it, when I'm trying to create a new repo by using git init. Im getting the following error:

"fatal: cannot symlink 'c:/Users/user/.talisman/bin/talisman_hook_script' 'C:/Users/user/Desktop/Git/Random/.git/hooks/pre-commit': Function not implemented"

Can you please tell me how it can be resolved.

**Comment by harinee** [comment] 2019-06-04 10:58
Hi @ni8walk3r, I just tried this out on a Windows machine, and seems to work fine for me.
Could you please give us a bit more details on:

1. Which Windows version are you using?
2. Did you install Talisman as a [global pre-commit hook](https://github.com/thoughtworks/talisman#installation-as-a-global-hook-template)?

**Comment by ni8walk3r** [comment] 2019-06-04 11:09
It's windows 10 and yest I installed it as a global pre-commit hook. Its working fine with Mac and Linux. But in windows after installing it, I'm not able to create a new empty repo by using git init. Tool is working fine on existing repos. Please refer to the attached screenshot @harinee 
![1](https://user-images.githubusercontent.com/50462098/58874784-526db680-86e7-11e9-9f8f-84a980d73472.png)

**Comment by harinee** [comment] 2019-06-04 17:53
I tried the exact same steps on Win10 too, worked for me.
@svishwanath-tw @aaquibzama-tw any suggestions?

**Comment by ni8walk3r** [comment] 2019-06-06 06:31
@harinee What was the settings you selected while installing talisamna?

**Comment by harinee** [comment] 2019-06-06 06:34
@ni8walk3r global pre-commit hook, set with all default selections.
One quick question - the other git repos which **did not** show an error for you, are they also in the same location? i.e. ~/Desktop/Git
I ask because Windows 10 has some new stricter permission on certain folders.

**Comment by ni8walk3r** [comment] 2019-06-06 06:45
@harinee repos which were present before installing talisman are working fine(and yes they are in the location you have mentioned above) after installing talisaman. Problem is after installing talisman I'm not able to create new empty repos.

**Comment by svishwanath-tw** [comment] 2019-06-06 18:37
@ni8walk3r : does you installation have multiple drives ?
In that case, git-bash might be trying to create a link across drives (partitions ?) and failing

**Comment by harinee** [comment] 2019-06-06 18:43
Is this helpful?
https://github.com/msysgit/msysgit/wiki/Why-am-I-getting-fatal-Invalid-symlink-....-Function-not-supported.-error-when-initcloneing

**Comment by svishwanath-tw** [comment] 2019-06-06 19:11
> Is this helpful?
> https://github.com/msysgit/msysgit/wiki/Why-am-I-getting-fatal-Invalid-symlink-....-Function-not-supported.-error-when-initcloneing

Excellent resource @harinee , beware though that this is valid only for NTFS filesystems (i wonder if anyone out there is using talisman on FAT32 windows machine , win98/ME anyone ?)

**Comment by ni8walk3r** [comment] 2019-06-07 06:17
@svishwanath-tw Yes, my installation has two drives namely C: & D:. But talisman was installed in C: Drive and the I'm trying to create the new empty repository in the same C: drive. @harinee Thanks for sharing the link, I'll take a loot at it.

**Comment by ni8walk3r** [comment] 2019-06-10 04:58
@harinee Solution present on the link you shared are not working.

**Comment by harinee** [comment] 2019-10-01 11:56
@ni8walk3r is this still reproducible? We tried and couldn't. Is there any further information we can take forward?

**Comment by divya1526** [comment] 2019-11-20 08:09
hi all ,
 i am trying to install talisman on developer workstation using husky talisman  can somebody please tell the steps how to do that  i have just run
1. npm install --save-dev husky-talisman
2. npm run husky-talisman pre-push

it seems to be fine but after that what should i do
please help me..

**Comment by harinee** [comment] 2020-06-18 12:27
@divya1526 we did not create the npm package for husky-talisman, so not sure how that works.
Maybe https://www.npmjs.com/~olmesm can help with that specifically?

But for Windows installation, did you try the way mentioned in Talisman's [ReadMe](https://github.com/thoughtworks/talisman#installation-as-a-global-hook-template)?
It is recommended to use git bash terminal.
`curl --silent  https://raw.githubusercontent.com/thoughtworks/talisman/master/global_install_scripts/install.bash > /tmp/install_talisman.bash && /bin/bash /tmp/install_talisman.bash`

If it still doesn't work, please raise a separate ticket with details.

**Comment by harinee** [comment] 2020-06-18 12:29
@ni8walk3r I just installed on a Win 10 right now again, for some testing. Worked fine for me yet again. Closing this issue for now. Please feel free to reopen if the issue still persists

**Closed by harinee** 2020-06-18 12:29 UTC
Labels: bug

**Comment by nasreenwahab** [comment] 2022-07-27 05:43
@harinee I am getting the exact same error in windows when I add a new repo to an existing folder in which talisman is already configured. Any idea how to resolve this.
![image](https://user-images.githubusercontent.com/106378327/181170095-480f51f4-8a30-4095-a3fc-8d3ffaf8d5b5.png)
