### ISSUE TITLE
not able to commit the file

### ISSUE THREAD

**Issue by richagupta8nov** [thoughtworks/talisman#207] opened 2020-07-09 10:39 UTC
@ not able to commit the file, if a file has secret data.

I have created the file vim - copy the error code, and then try to commit, but still not happening

**Comment by richagupta8nov** [comment] 2020-07-09 14:32
@harinee Request you to please reply

**Comment by harinee** [comment] 2020-07-12 09:20
@richagupta8nov please give more details in the issue.
Last we worked on your machine, it was working fine.
So please detail out what you tried and what errors you see.

**Comment by richagupta8nov** [comment] 2020-07-13 11:29
@harinee 

I have cloned a new repository, and copy the git hook file, in the hook folder, after that all works fine, but when I try to ignore the error, it was not happening.

To ignore the error, I open the vim editor, paste checksum code, and pressed:wq, it got saved, and again try to commit it, but it was still not ignoring it and showing error.

after that,  I have done git init, and took test repo, and paste the hook file, and try to ignore the error and try to commit, and all worked fine, I was able to ignore the error following the same step.

but in the cloned directory, i was not able to ignore the error, is it because I have cloned it??

**Comment by harinee** [comment] 2020-07-13 12:39
@richagupta8nov Just to debug further, could you please clone a different repo and try the same steps?
See if you get the same problem.
It will help narrow down to see if the issue is specific to the repo you have cloned now, or for any cloned repo in general

**Comment by richagupta8nov** [comment] 2020-07-14 06:18
@harinee 

I have cloned another repository, but it is still not working.

**Comment by harinee** [comment] 2020-07-14 16:13
Interesting. Other users seem to be using this fine.
You have a Windows 10 OS, correct?
Please confirm that your filename is correct, i.e., '.talismanrc'
Also, please see if you have a pre-existing hook in your repos, which is preventing hook chaining with talisman? You can also confirm from the file at ~/talisman_missed_repositories.paths ? If that is the case, then you need to chain your hooks https://github.com/thoughtworks/talisman#handling-existing-hooks

**Comment by richagupta8nov** [comment] 2020-07-15 12:34
@ yes i m working on window 10, I dont have any pre existing hook, so tht is not the issue.

**Comment by richagupta8nov** [comment] 2020-07-15 12:35
And reverified the name of the file name as well, using correct file name.

**Comment by harinee** [comment] 2020-09-21 02:14
Can this be closed? Is it working fine with the latest versions? @richagupta8nov

**Comment by harinee** [comment] 2021-05-30 17:46
Closing since we didn't hear back on this. Please feel free to re-open with comments, if it is still not working.

**Closed by harinee** 2021-05-30 17:46 UTC
Labels: bug
